### ISSUE TITLE
missing sign message method

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/jade-signer-rpc#15]
We are missing a key method to just `sign` messages. here is the `openrpc` for it:

![image](https://user-images.githubusercontent.com/364566/57044026-15149580-6c1e-11e9-9f68-5ff3cedf962f.png)

**Comment by shanejonas** [comment]
@r8d8 can you add this new method to sign? does this also need `additional`?

**Comment by r8d8** [comment]
maybe you mean this one:
https://github.com/etclabscore/jade-signer-rpc/blob/master/jade-signer-rs/src/rpc/serves.rs#L326 ?

**Comment by shanejonas** [comment]
oh good we already have it.

Can we make the `API` the same as laid out here, `passphrase` as its own param, same with `signTransaction`.

My main reasoning behind this is that `signTransaction` is very weird in that it takes passphrase with the transaction:

```
{
  to: "0x0",
  from: "0x0",
  // etc...
  passphrase: "foobar"
}
```


just seems really odd including `passphrase` there and not as its own param. so the idea is to pull that out to its own param, and then make it consistent everywhere else too.
