### ISSUE TITLE
take passphrase as another parameter for `signTransaction`

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/jade-signer-rpc#22]
when adding `sign`, it needs to take the passphrase separately than the data, unlike `signTransaction` (it takes passphrase with the `transaction`).

we should make this consistent, and take it as another parameter.

![image](https://user-images.githubusercontent.com/364566/57043899-b4855880-6c1d-11e9-9b9b-1eded64c2a10.png)

**Comment by shanejonas** [comment]
@r8d8 can you make the changes in the code to reflect this?

**Comment by r8d8** [comment]
it's already as separate parameter. Can you clarify, please, what do you mean.
