### ISSUE TITLE
remove ledger support

### ISSUE THREAD

**Issue by shanejonas** [etclabscore/jade-signer-rpc#40]
this gets us out of `libusb` as a dependency. as well as splits up the signing to only have `jade-signer` be a signer, Ledger can be another service that is run in the future if we need that support.

**Comment by shanejonas** [comment]
maybe in the future we wont need `libusb` as a dep: https://github.com/rust-embedded/wg/issues/40

**Comment by BelfordZ** [comment]
@mersinvald is this complete?

**Comment by mersinvald** [comment]
@BelfordZ yes
